default:
    image: kecorbin/hashi-gitlab-runner:latest
    before_script:
    - rm -rf .terraform
    - terraform --version
    - terraform init

stages:
  - validate
  - plan
  - apply
  - destroy

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    # Using parallelism=1 per https://github.com/ciscoecosystem/terraform-provider-aci/issues/4
    - terraform plan -parallelism=1
  allow_failure: true
  dependencies:
    - validate

apply:
  stage: apply
  script:
    # Use https://github.com/ciscoecosystem/terraform-provider-aci/issues/4
    - terraform apply -input=false -auto-approve -parallelism=1
  dependencies:
    - plan
  when: manual

destroy:
  stage: destroy
  script:
    # Using parallelism=1 per https://github.com/ciscoecosystem/terraform-provider-aci/issues/4
    - terraform destroy -auto-approve -parallelism=1
  dependencies:
    - apply
  when: manual
